<?php

namespace App\Traits;

use App\Models\Tahfidz\Mistake;
use Illuminate\Support\Arr;

trait QuranTrait
{
    public function getjuzMap()
    {
        return [
            1 => [1, 21],
            2 => [22, 41],
            3 => [42, 61],
            4 => [62, 81],
            5 => [82, 101],
            6 => [102, 121],
            7 => [122, 141],
            8 => [142, 161],
            9 => [162, 181],
            10 => [182, 201],
            11 => [202, 221],
            12 => [222, 241],
            13 => [242, 261],
            14 => [262, 281],
            15 => [282, 301],
            16 => [302, 321],
            17 => [322, 341],
            18 => [342, 361],
            19 => [362, 381],
            20 => [382, 401],
            21 => [402, 421],
            22 => [422, 441],
            23 => [442, 461],
            24 => [462, 481],
            25 => [482, 501],
            26 => [502, 521],
            27 => [522, 541],
            28 => [542, 561],
            29 => [562, 581],
            30 => [582, 604],
        ];
    }

    public function generateMistakesData(
        $examination,
        $configuration
    ) {
        $items = [];
        $mistakes = $this->generateMistakesTemplate($configuration);
        $rawScore = $this->generateRawScore($configuration);

        foreach ($this->generatePages($examination->juz) as $page) {
            $item = [
                'student_id' => $examination->student_id,
                'penguji_id' => $examination->penguji_id,
                'examination_id' => $examination->id,
                'tahun_ajaran' => $examination->tahun_ajaran,
                'semester' => $examination->semester,
                'juz' => $examination->juz,
                'page' => $page,
                'score' => 100,
                'raw_score' => json_encode($rawScore),
                'detail' => json_encode($mistakes),
                'is_nulled' => false,
                'periode' => 'pas',
                'created_at' => now(),
            ];

            array_push($items, $item);
        }

        // DB::table('tahfidz__mistakes')->insert($items);
        Mistake::insert($items);
    }

    public function generateRawScore($configuration, $nulled = false)
    {
        return collect($configuration)->map(function ($item) use ($nulled) {
            $item['maxScore'] = $nulled ? 0 : 100;
            return $item;
        })
            ->pluck('maxScore', 'aspek')
            ->toArray();
    }

    public function generateMistakesTemplate($configuration)
    {
        $collection = collect($configuration);
        $mistakes = $collection->map(function ($configItem) {
            return [
                'aspek' => $configItem['aspek'],
                'detail' => collect($configItem['bobot'])->map(fn($bobotItem) => [
                    'kriteria' => $bobotItem['kriteria'],
                    'counter' => 0,
                ])->pluck('counter', 'kriteria')->toArray(),
            ];
        })
            ->pluck('detail', 'aspek')
            ->toArray();
        return $mistakes;
    }

    public function generatePages($juz)
    {
        $juzMap = $this->getjuzMap();
        [$first, $last] = $juzMap[$juz];
        return range($first, $last);
    }

    public function getPoinKriteria($configuration)
    {
        $collection = collect($configuration);
        $aspects = $collection->map(function ($configItem) {
            return [
                'aspek' => $configItem['aspek'],
                'detail' => collect($configItem['bobot'])->pluck('poin', 'kriteria')->toArray(),
            ];
        })
            ->pluck('detail', 'aspek')
            ->toArray();
        return $aspects;
    }

    public static function getSurahNames()
    {
        return collect(static::getSurahsData())->map(function ($item) {
            $item['nama'] = $item['nomor'] . '. ' . $item['nama_surah'];
            return $item;
        })
            ->pluck('nama', 'nomor')/* ->sortKeys() */->toArray();
    }


    public static function getAyatsOfSurat($surat)
    {
        $surat = collect(static::getSurahsData())->where('nomor', $surat)->first();
        return [
            'awal' => 1,
            'akhir' => Arr::get($surat, 'jumlah_ayat'),
        ];
    }

    public static function getSurahsData()
    {
        $surahs = [
            [
                "nomor" => 1,
                "nama_surah" => "Al-Fatihah",
                "teks_arab" => "الفاتحة",
                "arti" => "Pembukaan",
                "jumlah_ayat" => 7,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 5,
            ],
            [
                "nomor" => 2,
                "nama_surah" => "Al-Baqarah",
                "teks_arab" => "البقرة",
                "arti" => "Sapi Betina",
                "jumlah_ayat" => 286,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 87,
            ],
            [
                "nomor" => 3,
                "nama_surah" => "Ali 'Imran",
                "teks_arab" => "آل عمران",
                "arti" => "Keluarga 'Imran",
                "jumlah_ayat" => 200,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 89,
            ],
            [
                "nomor" => 4,
                "nama_surah" => "An-Nisa'",
                "teks_arab" => "النّساء",
                "arti" => "Wanita",
                "jumlah_ayat" => 176,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 92,
            ],
            [
                "nomor" => 5,
                "nama_surah" => "Al-Ma'idah",
                "teks_arab" => "المائدة",
                "arti" => "Jamuan (hidangan makanan)",
                "jumlah_ayat" => 120,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 112,
            ],
            [
                "nomor" => 6,
                "nama_surah" => "Al-An'am",
                "teks_arab" => "الانعام",
                "arti" => "Hewan Ternak",
                "jumlah_ayat" => 165,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 55,
            ],
            [
                "nomor" => 7,
                "nama_surah" => "Al-A’raf",
                "teks_arab" => "الأعراف",
                "arti" => "Tempat yang tertinggi",
                "jumlah_ayat" => 206,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 39,
            ],
            [
                "nomor" => 8,
                "nama_surah" => "Al-Anfal",
                "teks_arab" => "الأنفال",
                "arti" => "Harta rampasan perang",
                "jumlah_ayat" => 75,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 88,
            ],
            [
                "nomor" => 9,
                "nama_surah" => "At-Taubah",
                "teks_arab" => "التوبة",
                "arti" => "Pengampunan",
                "jumlah_ayat" => 129,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 113,
            ],
            [
                "nomor" => 10,
                "nama_surah" => "Yunus",
                "teks_arab" => "يونس",
                "arti" => "Nabi Yunus",
                "jumlah_ayat" => 109,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 51,
            ],
            [
                "nomor" => 11,
                "nama_surah" => "Hud",
                "teks_arab" => "هود",
                "arti" => "Nabi Hud",
                "jumlah_ayat" => 123,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 52,
            ],
            [
                "nomor" => 12,
                "nama_surah" => "Yusuf",
                "teks_arab" => "يوسف",
                "arti" => "Nabi Yusuf",
                "jumlah_ayat" => 111,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 53,
            ],
            [
                "nomor" => 13,
                "nama_surah" => "Ar-Ra’d",
                "teks_arab" => "الرعد",
                "arti" => "Guruh (petir)",
                "jumlah_ayat" => 43,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 96,
            ],
            [
                "nomor" => 14,
                "nama_surah" => "Ibrahim",
                "teks_arab" => "إبراهيم",
                "arti" => "Nabi Ibrahim",
                "jumlah_ayat" => 52,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 72,
            ],
            [
                "nomor" => 15,
                "nama_surah" => "Al-Hijr",
                "teks_arab" => "الحجر",
                "arti" => "Gunung Al Hijr",
                "jumlah_ayat" => 99,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 54,
            ],
            [
                "nomor" => 16,
                "nama_surah" => "An-Nahl",
                "teks_arab" => "النحل",
                "arti" => "Lebah",
                "jumlah_ayat" => 128,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 70,
            ],
            [
                "nomor" => 17,
                "nama_surah" => "Al-Isra'",
                "teks_arab" => "الإسراء",
                "arti" => "Perjalanan Malam",
                "jumlah_ayat" => 111,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 50,
            ],
            [
                "nomor" => 18,
                "nama_surah" => "Al-Kahf",
                "teks_arab" => "الكهف",
                "arti" => "Penghuni-penghuni Gua",
                "jumlah_ayat" => 110,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 69,
            ],
            [
                "nomor" => 19,
                "nama_surah" => "Maryam",
                "teks_arab" => "مريم",
                "arti" => "Maryam (Maria)",
                "jumlah_ayat" => 98,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 44,
            ],
            [
                "nomor" => 20,
                "nama_surah" => "Ta Ha",
                "teks_arab" => "طه",
                "arti" => "Ta Ha",
                "jumlah_ayat" => 135,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 45,
            ],
            [
                "nomor" => 21,
                "nama_surah" => "Al-Anbiya",
                "teks_arab" => "الأنبياء",
                "arti" => "Nabi-Nabi",
                "jumlah_ayat" => 112,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 73,
            ],
            [
                "nomor" => 22,
                "nama_surah" => "Al-Hajj",
                "teks_arab" => "الحجّ",
                "arti" => "Haji",
                "jumlah_ayat" => 78,
                "tempat_turun" => "Madinah & Makkah",
                "urutan_pewahyuan" => 103,
            ],
            [
                "nomor" => 23,
                "nama_surah" => "Al-Mu’minun",
                "teks_arab" => "المؤمنون",
                "arti" => "Orang-orang mukmin",
                "jumlah_ayat" => 118,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 74,
            ],
            [
                "nomor" => 24,
                "nama_surah" => "An-Nur",
                "teks_arab" => "النور",
                "arti" => "Cahaya",
                "jumlah_ayat" => 64,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 102,
            ],
            [
                "nomor" => 25,
                "nama_surah" => "Al-Furqan",
                "teks_arab" => "الفرقان",
                "arti" => "Pembeda",
                "jumlah_ayat" => 77,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 42,
            ],
            [
                "nomor" => 26,
                "nama_surah" => "Asy-Syu'ara'",
                "teks_arab" => "الشعراء",
                "arti" => "Penyair",
                "jumlah_ayat" => 227,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 47,
            ],
            [
                "nomor" => 27,
                "nama_surah" => "An-Naml",
                "teks_arab" => "النمل",
                "arti" => "Semut",
                "jumlah_ayat" => 93,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 48,
            ],
            [
                "nomor" => 28,
                "nama_surah" => "Al-Qasas",
                "teks_arab" => "القصص",
                "arti" => "Kisah",
                "jumlah_ayat" => 88,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 49,
            ],
            [
                "nomor" => 29,
                "nama_surah" => "Al-'Ankabut",
                "teks_arab" => "العنكبوت",
                "arti" => "Laba-laba",
                "jumlah_ayat" => 69,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 85,
            ],
            [
                "nomor" => 30,
                "nama_surah" => "Ar-Rum",
                "teks_arab" => "الروم",
                "arti" => "Bangsa Romawi",
                "jumlah_ayat" => 60,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 84,
            ],
            [
                "nomor" => 31,
                "nama_surah" => "Luqman",
                "teks_arab" => "لقمان",
                "arti" => "Keluarga Luqman",
                "jumlah_ayat" => 34,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 57,
            ],
            [
                "nomor" => 32,
                "nama_surah" => "As-Sajdah",
                "teks_arab" => "السجدة",
                "arti" => "Sajdah",
                "jumlah_ayat" => 30,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 75,
            ],
            [
                "nomor" => 33,
                "nama_surah" => "Al-Ahzab",
                "teks_arab" => "الْأحزاب",
                "arti" => "Golongan-Golongan yang bersekutu",
                "jumlah_ayat" => 73,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 90,
            ],
            [
                "nomor" => 34,
                "nama_surah" => "Saba’",
                "teks_arab" => "سبأ",
                "arti" => "Kaum Saba'",
                "jumlah_ayat" => 54,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 58,
            ],
            [
                "nomor" => 35,
                "nama_surah" => "Fatir",
                "teks_arab" => "فاطر",
                "arti" => "Pencipta",
                "jumlah_ayat" => 45,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 43,
            ],
            [
                "nomor" => 36,
                "nama_surah" => "Ya Sin",
                "teks_arab" => "يس",
                "arti" => "Yaasiin",
                "jumlah_ayat" => 83,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 41,
            ],
            [
                "nomor" => 37,
                "nama_surah" => "As-Saffat",
                "teks_arab" => "الصافات",
                "arti" => "Barisan-barisan",
                "jumlah_ayat" => 182,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 56,
            ],
            [
                "nomor" => 38,
                "nama_surah" => "Sad",
                "teks_arab" => "ص",
                "arti" => "Shaad",
                "jumlah_ayat" => 88,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 38,
            ],
            [
                "nomor" => 39,
                "nama_surah" => "Az-Zumar",
                "teks_arab" => "الزمر",
                "arti" => "Rombongan-rombongan",
                "jumlah_ayat" => 75,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 59,
            ],
            [
                "nomor" => 40,
                "nama_surah" => "Ghafir",
                "teks_arab" => "غافر",
                "arti" => "Yang mengampuni",
                "jumlah_ayat" => 85,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 60,
            ],
            [
                "nomor" => 41,
                "nama_surah" => "Fussilat",
                "teks_arab" => "فصلت",
                "arti" => "Yang dijelaskan",
                "jumlah_ayat" => 54,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 61,
            ],
            [
                "nomor" => 42,
                "nama_surah" => "Asy-Syura",
                "teks_arab" => "الشورى",
                "arti" => "Musyawarah",
                "jumlah_ayat" => 53,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 62,
            ],
            [
                "nomor" => 43,
                "nama_surah" => "Az-Zukhruf",
                "teks_arab" => "الزخرف",
                "arti" => "Perhiasan",
                "jumlah_ayat" => 89,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 63,
            ],
            [
                "nomor" => 44,
                "nama_surah" => "Ad-Dukhan",
                "teks_arab" => "الدخان",
                "arti" => "Kabut",
                "jumlah_ayat" => 59,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 64,
            ],
            [
                "nomor" => 45,
                "nama_surah" => "Al-Jasiyah",
                "teks_arab" => "الجاثية",
                "arti" => "Yang bertekuk lutut",
                "jumlah_ayat" => 37,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 65,
            ],
            [
                "nomor" => 46,
                "nama_surah" => "Al-Ahqaf",
                "teks_arab" => "الَأحقاف",
                "arti" => "Bukit-bukit pasir",
                "jumlah_ayat" => 35,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 66,
            ],
            [
                "nomor" => 47,
                "nama_surah" => "Muhammad",
                "teks_arab" => "محمد",
                "arti" => "Nabi Muhammad",
                "jumlah_ayat" => 38,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 95,
            ],
            [
                "nomor" => 48,
                "nama_surah" => "Al-Fath",
                "teks_arab" => "الفتح",
                "arti" => "Kemenangan",
                "jumlah_ayat" => 29,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 111,
            ],
            [
                "nomor" => 49,
                "nama_surah" => "Al-Hujurat",
                "teks_arab" => "الحجرات",
                "arti" => "Kamar-kamar",
                "jumlah_ayat" => 18,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 106,
            ],
            [
                "nomor" => 50,
                "nama_surah" => "Qaf",
                "teks_arab" => "ق",
                "arti" => "Qaaf",
                "jumlah_ayat" => 45,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 34,
            ],
            [
                "nomor" => 51,
                "nama_surah" => "Az-Zariyat",
                "teks_arab" => "الذاريات",
                "arti" => "Angin yang menerbangkan",
                "jumlah_ayat" => 60,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 67,
            ],
            [
                "nomor" => 52,
                "nama_surah" => "At-Tur",
                "teks_arab" => "الطور",
                "arti" => "Bukit",
                "jumlah_ayat" => 49,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 76,
            ],
            [
                "nomor" => 53,
                "nama_surah" => "An-Najm",
                "teks_arab" => "النجم",
                "arti" => "Bintang",
                "jumlah_ayat" => 62,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 23,
            ],
            [
                "nomor" => 54,
                "nama_surah" => "Al-Qamar",
                "teks_arab" => "القمر",
                "arti" => "Bulan",
                "jumlah_ayat" => 55,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 37,
            ],
            [
                "nomor" => 55,
                "nama_surah" => "Ar-Rahman",
                "teks_arab" => "الرحمن",
                "arti" => "Yang Maha Pemurah",
                "jumlah_ayat" => 78,
                "tempat_turun" => "Madinah & Mekkah",
                "urutan_pewahyuan" => 97,
            ],
            [
                "nomor" => 56,
                "nama_surah" => "Al-Waqi’ah",
                "teks_arab" => "الواقعة",
                "arti" => "Hari Kiamat",
                "jumlah_ayat" => 96,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 46,
            ],
            [
                "nomor" => 57,
                "nama_surah" => "Al-Hadid",
                "teks_arab" => "الحديد",
                "arti" => "Besi",
                "jumlah_ayat" => 29,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 94,
            ],
            [
                "nomor" => 58,
                "nama_surah" => "Al-Mujadilah",
                "teks_arab" => "المجادلة",
                "arti" => "Wanita yang mengajukan gugatan",
                "jumlah_ayat" => 22,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 105,
            ],
            [
                "nomor" => 59,
                "nama_surah" => "Al-Hasyr",
                "teks_arab" => "الحشر",
                "arti" => "Pengusiran",
                "jumlah_ayat" => 24,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 101,
            ],
            [
                "nomor" => 60,
                "nama_surah" => "Al-Mumtahanah",
                "teks_arab" => "الممتحنة",
                "arti" => "Wanita yang diuji",
                "jumlah_ayat" => 13,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 91,
            ],
            [
                "nomor" => 61,
                "nama_surah" => "As-Saff",
                "teks_arab" => "الصف",
                "arti" => "Satu barisan",
                "jumlah_ayat" => 14,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 109,
            ],
            [
                "nomor" => 62,
                "nama_surah" => "Al-Jumu’ah",
                "teks_arab" => "الجمعة",
                "arti" => "Hari Jum’at",
                "jumlah_ayat" => 11,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 110,
            ],
            [
                "nomor" => 63,
                "nama_surah" => "Al-Munafiqun",
                "teks_arab" => "المنافقون",
                "arti" => "Orang-orang yang munafik",
                "jumlah_ayat" => 11,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 104,
            ],
            [
                "nomor" => 64,
                "nama_surah" => "At-Tagabun",
                "teks_arab" => "التغابن",
                "arti" => "Hari dinampakkan kesalahan-kesalahan",
                "jumlah_ayat" => 18,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 108,
            ],
            [
                "nomor" => 65,
                "nama_surah" => "At-Talaq",
                "teks_arab" => "الطلاق",
                "arti" => "Talak",
                "jumlah_ayat" => 12,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 99,
            ],
            [
                "nomor" => 66,
                "nama_surah" => "At-Tahrim",
                "teks_arab" => "التحريم",
                "arti" => "Mengharamkan",
                "jumlah_ayat" => 12,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 107,
            ],
            [
                "nomor" => 67,
                "nama_surah" => "Al-Mulk",
                "teks_arab" => "الملك",
                "arti" => "Kerajaan",
                "jumlah_ayat" => 30,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 77,
            ],
            [
                "nomor" => 68,
                "nama_surah" => "Al-Qalam",
                "teks_arab" => "القلم",
                "arti" => "Pena",
                "jumlah_ayat" => 52,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 2,
            ],
            [
                "nomor" => 69,
                "nama_surah" => "Al-Haqqah",
                "teks_arab" => "الحآقة",
                "arti" => "Hari kiamat",
                "jumlah_ayat" => 52,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 78,
            ],
            [
                "nomor" => 70,
                "nama_surah" => "Al-Ma’arij",
                "teks_arab" => "المعارج",
                "arti" => "Tempat naik",
                "jumlah_ayat" => 44,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 79,
            ],
            [
                "nomor" => 71,
                "nama_surah" => "Nuh",
                "teks_arab" => "نوح",
                "arti" => "Nabi Nuh",
                "jumlah_ayat" => 28,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 71,
            ],
            [
                "nomor" => 72,
                "nama_surah" => "Al-Jinn",
                "teks_arab" => "الجن",
                "arti" => "Jin",
                "jumlah_ayat" => 28,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 40,
            ],
            [
                "nomor" => 73,
                "nama_surah" => "Al-Muzzammil",
                "teks_arab" => "المزمل",
                "arti" => "Orang yang berselimut",
                "jumlah_ayat" => 20,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 3,
            ],
            [
                "nomor" => 74,
                "nama_surah" => "Al-Muddassir",
                "teks_arab" => "المدثر",
                "arti" => "Orang yang berkemul",
                "jumlah_ayat" => 56,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 4,
            ],
            [
                "nomor" => 75,
                "nama_surah" => "Al-Qiyamah",
                "teks_arab" => "القيامة",
                "arti" => "Kiamat",
                "jumlah_ayat" => 40,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 31,
            ],
            [
                "nomor" => 76,
                "nama_surah" => "Al-Insan",
                "teks_arab" => "الإنسان",
                "arti" => "Manusia",
                "jumlah_ayat" => 31,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 98,
            ],
            [
                "nomor" => 77,
                "nama_surah" => "Al-Mursalat",
                "teks_arab" => "المرسلات",
                "arti" => "Malaikat-Malaikat Yang Diutus",
                "jumlah_ayat" => 50,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 33,
            ],
            [
                "nomor" => 78,
                "nama_surah" => "An-Naba’",
                "teks_arab" => "النبأ",
                "arti" => "Berita besar",
                "jumlah_ayat" => 40,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 80,
            ],
            [
                "nomor" => 79,
                "nama_surah" => "An-Nazi’at",
                "teks_arab" => "النازعات",
                "arti" => "Malaikat-Malaikat Yang Mencabut",
                "jumlah_ayat" => 46,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 81,
            ],
            [
                "nomor" => 80,
                "nama_surah" => "'Abasa",
                "teks_arab" => "عبس",
                "arti" => "Ia Bermuka masam",
                "jumlah_ayat" => 42,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 24,
            ],
            [
                "nomor" => 81,
                "nama_surah" => "At-Takwir",
                "teks_arab" => "التكوير",
                "arti" => "Menggulung",
                "jumlah_ayat" => 29,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 7,
            ],
            [
                "nomor" => 82,
                "nama_surah" => "Al-Infitar",
                "teks_arab" => "الإنفطار",
                "arti" => "Terbelah",
                "jumlah_ayat" => 19,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 82,
            ],
            [
                "nomor" => 83,
                "nama_surah" => "Al-Mutaffifin",
                "teks_arab" => "المطففين",
                "arti" => "Orang-orang yang curang",
                "jumlah_ayat" => 36,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 86,
            ],
            [
                "nomor" => 84,
                "nama_surah" => "Al-Insyiqaq",
                "teks_arab" => "الإنشقاق",
                "arti" => "Terbelah",
                "jumlah_ayat" => 25,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 83,
            ],
            [
                "nomor" => 85,
                "nama_surah" => "Al-Buruj",
                "teks_arab" => "البروج",
                "arti" => "Gugusan bintang",
                "jumlah_ayat" => 22,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 27,
            ],
            [
                "nomor" => 86,
                "nama_surah" => "At-Tariq",
                "teks_arab" => "الطارق",
                "arti" => "Yang datang di malam hari",
                "jumlah_ayat" => 17,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 36,
            ],
            [
                "nomor" => 87,
                "nama_surah" => "Al-A’la",
                "teks_arab" => "الأعلى",
                "arti" => "Yang paling tinggi",
                "jumlah_ayat" => 19,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 8,
            ],
            [
                "nomor" => 88,
                "nama_surah" => "Al-Gasyiyah",
                "teks_arab" => "الغاشية",
                "arti" => "Hari Pembalasan",
                "jumlah_ayat" => 26,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 68,
            ],
            [
                "nomor" => 89,
                "nama_surah" => "Al-Fajr",
                "teks_arab" => "الفجر",
                "arti" => "Fajar",
                "jumlah_ayat" => 30,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 10,
            ],
            [
                "nomor" => 90,
                "nama_surah" => "Al-Balad",
                "teks_arab" => "البلد",
                "arti" => "Negeri",
                "jumlah_ayat" => 20,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 35,
            ],
            [
                "nomor" => 91,
                "nama_surah" => "Asy-Syams",
                "teks_arab" => "الشمس",
                "arti" => "Matahari",
                "jumlah_ayat" => 15,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 26,
            ],
            [
                "nomor" => 92,
                "nama_surah" => "Al-Lail",
                "teks_arab" => "اليل",
                "arti" => "Malam",
                "jumlah_ayat" => 21,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 9,
            ],
            [
                "nomor" => 93,
                "nama_surah" => "Ad-Duha",
                "teks_arab" => "الضحى",
                "arti" => "Waktu matahari sepenggalahan naik (Dhuha)",
                "jumlah_ayat" => 11,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 11,
            ],
            [
                "nomor" => 94,
                "nama_surah" => "Al-Insyirah",
                "teks_arab" => "الإنشراح",
                "arti" => "Melapangkan",
                "jumlah_ayat" => 8,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 12,
            ],
            [
                "nomor" => 95,
                "nama_surah" => "At-Tin",
                "teks_arab" => "التينِ",
                "arti" => "Buah Tin",
                "jumlah_ayat" => 8,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 28,
            ],
            [
                "nomor" => 96,
                "nama_surah" => "Al-'Alaq",
                "teks_arab" => "العلق",
                "arti" => "Segumpal Darah",
                "jumlah_ayat" => 19,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 1,
            ],
            [
                "nomor" => 97,
                "nama_surah" => "Al-Qadr",
                "teks_arab" => "القدرِ",
                "arti" => "Kemuliaan",
                "jumlah_ayat" => 5,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 25,
            ],
            [
                "nomor" => 98,
                "nama_surah" => "Al-Bayyinah",
                "teks_arab" => "البينة",
                "arti" => "Pembuktian",
                "jumlah_ayat" => 8,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 100,
            ],
            [
                "nomor" => 99,
                "nama_surah" => "Az-Zalzalah",
                "teks_arab" => "الزلزلة",
                "arti" => "Kegoncangan",
                "jumlah_ayat" => 8,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 93,
            ],
            [
                "nomor" => 100,
                "nama_surah" => "Al-'Adiyat",
                "teks_arab" => "العاديات",
                "arti" => "Berlari kencang",
                "jumlah_ayat" => 11,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 14,
            ],
            [
                "nomor" => 101,
                "nama_surah" => "Al-Qari'ah",
                "teks_arab" => "القارعة",
                "arti" => "Hari Kiamat",
                "jumlah_ayat" => 11,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 30,
            ],
            [
                "nomor" => 102,
                "nama_surah" => "At-Takasur",
                "teks_arab" => "التكاثر",
                "arti" => "Bermegah-megahan",
                "jumlah_ayat" => 8,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 16,
            ],
            [
                "nomor" => 103,
                "nama_surah" => "Al-'Asr",
                "teks_arab" => "العصر",
                "arti" => "Masa/Waktu",
                "jumlah_ayat" => 3,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 13,
            ],
            [
                "nomor" => 104,
                "nama_surah" => "Al-Humazah",
                "teks_arab" => "الهمزة",
                "arti" => "Pengumpat",
                "jumlah_ayat" => 9,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 32,
            ],
            [
                "nomor" => 105,
                "nama_surah" => "Al-Fil",
                "teks_arab" => "الفيل",
                "arti" => "Gajah",
                "jumlah_ayat" => 5,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 19,
            ],
            [
                "nomor" => 106,
                "nama_surah" => "Quraisy",
                "teks_arab" => "قريش",
                "arti" => "Suku Quraisy",
                "jumlah_ayat" => 4,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 29,
            ],
            [
                "nomor" => 107,
                "nama_surah" => "Al-Ma’un",
                "teks_arab" => "الماعون",
                "arti" => "Barang-barang yang berguna",
                "jumlah_ayat" => 7,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 17,
            ],
            [
                "nomor" => 108,
                "nama_surah" => "Al-Kausar",
                "teks_arab" => "الكوثر",
                "arti" => "Nikmat yang berlimpah",
                "jumlah_ayat" => 3,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 15,
            ],
            [
                "nomor" => 109,
                "nama_surah" => "Al-Kafirun",
                "teks_arab" => "الكافرون",
                "arti" => "Orang-orang kafir",
                "jumlah_ayat" => 6,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 18,
            ],
            [
                "nomor" => 110,
                "nama_surah" => "An-Nasr",
                "teks_arab" => "النصر",
                "arti" => "Pertolongan",
                "jumlah_ayat" => 3,
                "tempat_turun" => "Madinah",
                "urutan_pewahyuan" => 114,
            ],
            [
                "nomor" => 111,
                "nama_surah" => "Al-Lahab",
                "teks_arab" => "اللهب",
                "arti" => "Gejolak Api/ Sabut",
                "jumlah_ayat" => 5,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 6,
            ],
            [
                "nomor" => 112,
                "nama_surah" => "Al-Ikhlas",
                "teks_arab" => "الإخلاص",
                "arti" => "Keesaan Allah",
                "jumlah_ayat" => 4,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 22,
            ],
            [
                "nomor" => 113,
                "nama_surah" => "Al-Falaq",
                "teks_arab" => "الفلق",
                "arti" => "Waktu Subuh",
                "jumlah_ayat" => 5,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 20,
            ],
            [
                "nomor" => 114,
                "nama_surah" => "An-Nas",
                "teks_arab" => "الناس",
                "arti" => "Umat Manusia",
                "jumlah_ayat" => 6,
                "tempat_turun" => "Mekkah",
                "urutan_pewahyuan" => 21,
            ],
        ];

        return $surahs;
    }
}
